"""
User-facing LLens AI Analyst -- Phase 11 of the LLens Multi-Log Analysis
Strategy.

Ollama-only by design (see backend/api/routes/ai.py's /api/ai/config) -- the
payment/transaction data this endpoint reasons over is sensitive, so no
cloud AI provider is ever used here or anywhere else in this app.

Every answer is generated by backend/llm/ai_analyst.py's AIAnalystAssistant
from the SAME trusted AnalysisBundle every other Phase 10 analytics route
uses -- the AI cannot see raw log rows and cannot invent a metric/SQL/join
that Phase 2-10 didn't already compute (see backend/analysis/query_tools.py).
Every question is audit-logged (backend/llm/audit.py): user, timestamp,
question, data sources used, result, model/engine version.
"""
import asyncio
from typing import Optional

from fastapi import APIRouter, Depends, Query
from pydantic import BaseModel

from backend.analysis.pipeline import ALL_PAYMENT_FAMILIES, ENGINE_VERSION, run_analysis_pipeline
from backend.api.date_range import resolve_date_range
from backend.api.deps import (
    get_ai_analyst_assistant,
    get_ai_analyst_audit_log,
    get_current_user,
    get_db,
    get_profile_manager,
    require_admin,
)
from backend.auth.service import AuthenticatedUser
from backend.core.store import DatabaseManager
from backend.llm.ai_analyst import AIAnalystAssistant
from backend.llm.audit import AIAnalystAuditLog

router = APIRouter(prefix="/api/ai-analyst", tags=["ai-analyst"])


class AskRequest(BaseModel):
    question: str


@router.post("/ask")
async def ask(
    body: AskRequest,
    lookback_hours: int = Query(24 * 7, ge=1, le=24 * 365),
    date_from: Optional[str] = Query(None),
    date_to: Optional[str] = Query(None),
    user: AuthenticatedUser = Depends(get_current_user),
    db: DatabaseManager = Depends(get_db),
    assistant: AIAnalystAssistant = Depends(get_ai_analyst_assistant),
    audit_log: AIAnalystAuditLog = Depends(get_ai_analyst_audit_log),
):
    resolved_from, resolved_to = resolve_date_range(lookback_hours, date_from, date_to)
    bundle = run_analysis_pipeline(db, date_from=resolved_from, date_to=resolved_to, profile_manager=get_profile_manager())

    # Run the Ollama LLM calls in a dedicated thread so that slow
    # inference (tool selection + narration) does not block FastAPI's
    # shared request thread pool -- other users' page loads stay
    # responsive while one person's AI question is processing.
    answer = await asyncio.to_thread(assistant.ask, body.question, bundle)

    audit_log.record(
        user_id=user.user_id,
        username=user.username,
        question=body.question,
        tool_used=answer.tool_used,
        tool_parameters=answer.tool_parameters,
        data_sources_used=list(ALL_PAYMENT_FAMILIES),
        result_summary=answer.answer,
        confidence=answer.confidence.value if answer.confidence else None,
        model_name=f"ollama:{assistant.client.model}",
        engine_version=ENGINE_VERSION,
        ai_available=answer.ai_available,
    )

    return answer.model_dump()


@router.get("/audit-log")
def get_audit_log(
    limit: int = Query(100, ge=1, le=1000),
    _user: AuthenticatedUser = Depends(require_admin),
    audit_log: AIAnalystAuditLog = Depends(get_ai_analyst_audit_log),
):
    return {"entries": audit_log.list_recent(limit=limit)}
